In [3]:
import tensorflow as tf
import numpy as np

### 1. Creating Tensors in TensorFlow

#### From Constants

In [6]:
# Rank 0
scalar = tf.constant(3)

# Rank 1
vector = tf.constant([1,2,3])

# Rank 2
matrix = tf.constant([[1,2], [3,4]])

# Rank 3+
tensor_3d = tf.constant([[[1,2], [3,4]],
                        [[5,6], [7,8]]
                        ])

print(scalar)
print('_'*40)
print(vector)
print('_'*40)
print(matrix)
print('_'*40)
print(tensor_3d)

tf.Tensor(3, shape=(), dtype=int32)
________________________________________
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
________________________________________
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
________________________________________
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#### From NumPy Arrays

In [9]:
np_array = np.array([[1,2], [3,4]])

tensor_from_numpy = tf.convert_to_tensor(np_array, dtype=tf.float32)

print(tensor_from_numpy)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


#### Using TF funstions

In [11]:
# Tensor of zeros
zero_tensor = tf.zeros([3,3])
print(zero_tensor)
print('_'*40)

# Tensor of ones
ones_tensor = tf.ones([2,3])
print(ones_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
________________________________________
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [26]:
# Random
random_normal_tensor = tf.random.normal([2,3], mean=0, stddev=1)
print(random_normal_tensor)
print('_'*80)

random_uniform_tensor = tf.random.uniform([2,3], minval=0, maxval=10)
print(random_uniform_tensor)

tf.Tensor(
[[ 1.6628428   0.93898857 -1.0541383 ]
 [-0.8155626   0.25823978 -0.5665658 ]], shape=(2, 3), dtype=float32)
________________________________________________________________________________
tf.Tensor(
[[0.28122306 0.36711574 8.333291  ]
 [1.7592084  0.44962883 3.7781    ]], shape=(2, 3), dtype=float32)


In [27]:
linspace_tensor = tf.linspace(1.0, 10.0, num=10)  # 10 values from 1 to 10
print(linspace_tensor)
print('_'*80)

range_tensor = tf.range(0, 10, 2)  # Values from 0 to 10 with step size 2
print(range_tensor)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)
________________________________________________________________________________
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [28]:
variable_tensor = tf.Variable([1, 2, 3])
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


### 2. Manipulating Tensors

#### a. Element-wise Operations

In [31]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

result_add = a + b
print(result_add)

result_mul = a * b
print(result_mul)

result_exp = tf.pow(a, 2)
print(result_exp)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)


#### b. Matrix Operations

In [38]:
matrix_a = tf.constant([[1,2],[3,4]])
matrix_b = tf.constant([[5,6],[7,8]])

result_dot = tf.matmul(matrix_a, matrix_b)
print(result_dot)

result_transpose = tf.transpose(matrix_a)
print(result_transpose)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


#### c. Reshaping and Resizing

In [49]:
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])

# Reshape from 2x3 to 3x2
reshaped_tensor = tf.reshape(tensor_2d, [6,1])
print(reshaped_tensor)

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)


#### d. Slicing and Indexing

In [50]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print(tensor[1])  # Second row

# Slicing
print(tensor[:, 1])  # Second column
print(tensor[1, 1:3])  # Second row, second and third columns

tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


#### e. Concatenation and Stacking

In [51]:
# Concatenation
tensor_1 = tf.constant([1, 2])
tensor_2 = tf.constant([3, 4])
concat_tensor = tf.concat([tensor_1, tensor_2], axis=0)  # Concatenate along the first axis (rows)
print(concat_tensor)

# Stacking
stacked_tensor = tf.stack([tensor_1, tensor_2], axis=0)  # Stack tensors into a new axis
print(stacked_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### f. Broadcasting


In [52]:
a = tf.constant([1, 2, 3])
b = tf.constant([[1], [2], [3]])

result_broadcast = a + b  # Broadcasting adds 'a' to each row of 'b'
print(result_broadcast)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)
