In [62]:
import pandas as pd
sales = pd.read_csv('Black Friday/train.csv')
# sales.head()

In [63]:
sales.shape

(550068, 12)

In [64]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [44]:
import numpy as np
np.sort(sales.Product_Category_1.unique())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int64)

In [46]:
np.sort(sales.Product_Category_2.unique())

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., nan])

In [66]:
np.sort(sales.Product_Category_3.unique())

array([ 3.,  4.,  5.,  6.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., nan])

In [65]:
df2 = sales.copy(deep=True)

In [67]:
df2.shape

(550068, 12)

In [75]:
df2['Product_Category_1'] = df2['Product_Category_1'].astype('str')
df2['Product_Category_2'] = df2['Product_Category_2'].astype('str')
df2['Product_Category_3'] = df2['Product_Category_3'].astype('str')

In [76]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype 
---  ------                      --------------   ----- 
 0   User_ID                     550068 non-null  int64 
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64 
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64 
 8   Product_Category_1          550068 non-null  object
 9   Product_Category_2          550068 non-null  object
 10  Product_Category_3          550068 non-null  object
 11  Purchase                    550068 non-null  int64 
dtypes: int64(4), object(8)
memory usage: 50.4+ MB


In [77]:
from sklearn.impute import SimpleImputer
simpImp = SimpleImputer(strategy='constant', fill_value='unknown')

df2[['Product_Category_2', 'Product_Category_3']] = simpImp.fit_transform(df2[['Product_Category_2', 'Product_Category_3']])
df2

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status Product_Category_1  \
0                               2               0                  3   
1                               2               0                  1   
2                               2               0                 12   
3                               2               0                 12   
4                              4+               0                  8   
...                           ...             ...                ...   
550063                          1               1                 20   
550064                          3               0                 20   
550065                         4+               1                 20   
550066                          2               0                 20   
550067                         4+               1                 20   

       Product_Category_2 Product_Category_3  Purchase  
0                 unknown            unknown      8370  
1                     6.0               14.0     15200  
2                 unknown            unknown      1422  
3                    14.0            unknown      1057  
4                 unknown            unknown      7969  
...                   ...                ...       ...  
550063            unknown            unknown       368  
550064            unknown            unknown       371  
550065            unknown            unknown       137  
550066            unknown            unknown       365  
550067            unknown            unknown       490  

[550068 rows x 12 columns]

In [92]:
X, y = df2.drop(columns=['User_ID', 'Product_ID', 'Purchase']), df2['Purchase']

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)

In [94]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer, make_column_selector
ohe = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore').set_output(transform='pandas')

ct = make_column_transformer(
        (ohe, make_column_selector(dtype_include=object)),
        ('passthrough', make_column_selector(dtype_exclude=object)),
        verbose_feature_names_out=False).set_output(transform='pandas')

X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [95]:
X_train.shape

(385047, 66)

In [87]:
X_train

Gender_M  Age_18-25  Age_26-35  Age_36-45  Age_46-50  Age_51-55  \
415557       1.0        1.0        0.0        0.0        0.0        0.0   
261734       1.0        0.0        1.0        0.0        0.0        0.0   
413450       1.0        1.0        0.0        0.0        0.0        0.0   
210594       1.0        0.0        0.0        0.0        0.0        1.0   
63072        1.0        0.0        1.0        0.0        0.0        0.0   
...          ...        ...        ...        ...        ...        ...   
478609       0.0        1.0        0.0        0.0        0.0        0.0   
516439       1.0        0.0        1.0        0.0        0.0        0.0   
211136       1.0        1.0        0.0        0.0        0.0        0.0   
899          1.0        0.0        0.0        0.0        1.0        0.0   
242082       1.0        0.0        1.0        0.0        0.0        0.0   

        Age_55+  City_Category_B  City_Category_C  \
415557      0.0              1.0              0.0   
261734      0.0              1.0              0.0   
413450      0.0              1.0              0.0   
210594      0.0              0.0              0.0   
63072       0.0              1.0              0.0   
...         ...              ...              ...   
478609      0.0              1.0              0.0   
516439      0.0              0.0              1.0   
211136      0.0              1.0              0.0   
899         0.0              0.0              1.0   
242082      0.0              1.0              0.0   

        Stay_In_Current_City_Years_1  ...  Product_Category_3_18.0  \
415557                           0.0  ...                      0.0   
261734                           0.0  ...                      0.0   
413450                           1.0  ...                      0.0   
210594                           0.0  ...                      0.0   
63072                            1.0  ...                      0.0   
...                              ...  ...                      ...   
478609                           0.0  ...                      0.0   
516439                           0.0  ...                      0.0   
211136                           0.0  ...                      0.0   
899                              0.0  ...                      0.0   
242082                           0.0  ...                      0.0   

        Product_Category_3_3.0  Product_Category_3_4.0  \
415557                     0.0                     0.0   
261734                     0.0                     0.0   
413450                     0.0                     0.0   
210594                     0.0                     0.0   
63072                      0.0                     0.0   
...                        ...                     ...   
478609                     0.0                     0.0   
516439                     0.0                     0.0   
211136                     0.0                     0.0   
899                        0.0                     0.0   
242082                     0.0                     0.0   

        Product_Category_3_5.0  Product_Category_3_6.0  \
415557                     0.0                     0.0   
261734                     0.0                     0.0   
413450                     0.0                     0.0   
210594                     0.0                     0.0   
63072                      0.0                     0.0   
...                        ...                     ...   
478609                     0.0                     0.0   
516439                     0.0                     0.0   
211136                     0.0                     0.0   
899                        0.0                     0.0   
242082                     0.0                     0.0   

        Product_Category_3_8.0  Product_Category_3_9.0  \
415557                     0.0                     0.0   
261734                     0.0                     0.0   
413450                     0.0                     0.0   
210

In [88]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score 
best_rf = RandomForestRegressor(random_state=24)
best_rf.fit(X_train, y_train)
y_pred = best_rf.predict(X_test)

In [89]:
r2_score(y_test, y_pred)

0.6346457138667188

### Inferencing

In [98]:
X_train, y_train = ct.fit_transform(X), y
X_test = pd.read_csv('Black Friday/test.csv')
X_test.fillna(0, inplace=True)

In [102]:
X_test['Product_Category_1'] = X_test['Product_Category_1'].astype('str')
X_test['Product_Category_2'] = X_test['Product_Category_2'].astype('str')
X_test['Product_Category_3'] = X_test['Product_Category_3'].astype('str')

simpImp = SimpleImputer(strategy='constant', fill_value='unknown')
X_test[['Product_Category_2', 'Product_Category_3']] = simpImp.fit_transform(X_test[['Product_Category_2', 'Product_Category_3']])

X_test = ct.transform(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:241: UserWarning: Found unknown categories in columns [5, 6] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [103]:
best_rf.fit(X_train, y_train)
y_pred = best_rf.predict(X_test)

In [108]:
submit = pd.read_csv('Black Friday/sample_submission.csv')
submit.head()

Purchase  User_ID Product_ID
0       100  1000004  P00128942
1       100  1000009  P00113442
2       100  1000010  P00288442
3       100  1000010  P00145342
4       100  1000011  P00053842

In [113]:
y_pred.shape

(233599,)

In [109]:
submit['Purchase'] = y_pred

In [114]:
submit.to_csv('submit.csv', index=False)

In [115]:
submit.shape

(233599, 3)